import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '202012211656'
down_revision = '202012201650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('status', sa.Enum('in_progress', 'finished', name='gamestatus', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    pass
